config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

# resources :restaurants, only: [:index, :new, :create, :show] do
#   resources :reviews, only: [:new, :create]
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

# before_action :set_restaurant, only: %i[new create]

# def create
#   @review = Review.new(review_params)
#   @review.restaurant = @restaurant
#   @review.save

#   if @review.save
#     redirect_to restaurant_path(@restaurant)
#   else
#     render :new, status: :unprocessable_entity
#   end
# end

# private

# def set_restaurant
#   @restaurant = Restaurant.find(params[:restaurant_id])
# end

# def review_params
#   params.require(:review).permit(:rating, :content)
# end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @list.update(list_params)

    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>new sBookmar</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Create bm", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <div class="header_logo"><%= image_tag "logo.png", alt: "web logo", width: 50 %> Phoenix movies</p></div>

      <div class="header_links">
        <%= link_to "My lists", lists_path(@lists) %>
        <%= link_to "New list", new_list_path(@list) %>
      </div>
    </header>

    <%= yield %>

    <footer>
      Phoenix Movies © 2023. All rights reserved
    </footer>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit" %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <div class="form-container">
    <div class="form-header">
      <h1>Edit list</h1>
    </div>

    <div class="form-body">
      <%= render "form", list: @list %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="hero">
  <div class="hero-info">
    <h1>Save any kind of movies</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam repellat laudantium aperiam ea quasi a consequuntur earum, qui fugiat.</p>
  </div>
</div>


<div class="container">
  <div class="lists">
    <div class="lists-header">
      <h2>My lists</h2>
      <%= link_to "+ ADD", new_list_path(@list) %>
    </div>

    <div class="cards">
      <% @lists.each do |list| %>
        <div class="card list-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>')">
          <div class="list-info">
            <h3><%= link_to list.name, list_path(list) %></h3>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="form-container">
    <div class="form-header">
      <h1>Create list</h1>
    </div>

    <div class="form-body">
      <%= render "form", list: @list %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="hero-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')">
  <div class="hero-list-info">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <div class="movie-lists">
    <div class="movie-lists-header">
        <h2>My movies</h2>
        <div class="movie-lists-btn">
          <%= link_to new_list_bookmark_path(@list) do %>
            <i class="fa-solid fa-plus" style="margin-right: 5px"></i>
            Add movie
          <% end %>

          <%= link_to edit_list_path(@list) do %>
            <i class="fa-solid fa-pen" style="margin-right: 5px"></i>
            Edit list
          <% end %>

          <%= link_to list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-trash" style="margin-right: 5px"></i>
            Delete list
          <% end %>
        </div>
      </div>

      <div class="cards cards-movie">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card movie">
            <div class="movie-img">
              <%= image_tag bookmark.movie.poster_url, alt: "Movie poster", width: 200 %>
            </div>

            <div class="movie-info">
              <h3><%= bookmark.movie.title %></h3>
              <p><%= bookmark.movie.overview %></p>


              <div class="movie-comment">
                <p><i class="fa-solid fa-quote-left" style="margin-right: 10px"></i><%= bookmark.comment %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/movies/home.html.erb
<h1>Movies#home</h1>
<p>Find me in app/views/movies/home.html.erb</p>